use super::gold::{
    GoldCommentTermination, GoldDiagnostic, GoldDiagnosticCode, GoldDiagnosticContext,
    GoldDiagnosticSubject, GoldFixture, GoldGroup, GoldHashType, GoldLexicalItem, GoldNumber,
    GoldPreprocessedUnit, GoldRange, GoldRecovery, GoldResourceKind, GoldSign, GoldTokenKind,
};

fn r(start: usize, end: usize) -> GoldRange {
    GoldRange::new(start, end)
}

fn token(start: usize, end: usize, kind: GoldTokenKind) -> GoldLexicalItem {
    GoldLexicalItem::Token {
        range: r(start, end),
        kind,
    }
}

fn closed_comment(start: usize, end: usize) -> GoldLexicalItem {
    GoldLexicalItem::Comment {
        range: r(start, end),
        open: r(start, start + 2),
        termination: GoldCommentTermination::Closed {
            close: r(end - 2, end),
        },
    }
}

fn eof_comment(start: usize, end: usize) -> GoldLexicalItem {
    GoldLexicalItem::Comment {
        range: r(start, end),
        open: r(start, start + 2),
        termination: GoldCommentTermination::EndOfInput,
    }
}

fn unit(semantic: char, start: usize, end: usize) -> GoldPreprocessedUnit {
    GoldPreprocessedUnit {
        semantic,
        raw: r(start, end),
    }
}

fn diagnostic(
    code: GoldDiagnosticCode,
    start: usize,
    end: usize,
    context: GoldDiagnosticContext,
    recovery: GoldRecovery,
    subject: GoldDiagnosticSubject,
) -> GoldDiagnostic {
    GoldDiagnostic {
        code,
        location: r(start, end),
        context,
        recovery,
        subject,
    }
}

fn integer(sign: Option<GoldSign>, digits: &'static str) -> GoldNumber {
    GoldNumber::integer(sign, digits)
}

fn number(
    sign: Option<GoldSign>,
    integer_digits: &'static str,
    fraction_digits: &'static str,
    exponent_sign: Option<GoldSign>,
    exponent_digits: Option<&'static str>,
) -> GoldNumber {
    GoldNumber::number(
        sign,
        integer_digits,
        fraction_digits,
        exponent_sign,
        exponent_digits,
    )
}

pub(super) fn specification_fixtures() -> Vec<GoldFixture> {
    vec![
        GoldFixture::complete(
            "CSS-INPUT-EMPTY-001",
            GoldGroup::InputPreprocessing,
            1001,
            "",
            0,
            None,
            vec![],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-INPUT-BOM-ONLY-001",
            GoldGroup::InputPreprocessing,
            1002,
            "\u{feff}",
            3,
            Some(r(0, 3)),
            vec![],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-INPUT-BOM-TOKEN-001",
            GoldGroup::InputPreprocessing,
            1003,
            "\u{feff}a",
            4,
            Some(r(0, 3)),
            vec![token(3, 4, GoldTokenKind::Ident("a"))],
            vec![],
            vec![unit('a', 3, 4)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-NONLEADING-FEFF-001",
            GoldGroup::InputPreprocessing,
            1004,
            "a\u{feff}",
            4,
            None,
            vec![token(0, 4, GoldTokenKind::Ident("a\u{feff}"))],
            vec![],
            vec![unit('a', 0, 1), unit('\u{feff}', 1, 4)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-LF-001",
            GoldGroup::InputPreprocessing,
            1005,
            "\n",
            1,
            None,
            vec![token(0, 1, GoldTokenKind::Whitespace)],
            vec![],
            vec![unit('\n', 0, 1)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-CR-001",
            GoldGroup::InputPreprocessing,
            1006,
            "\r",
            1,
            None,
            vec![token(0, 1, GoldTokenKind::Whitespace)],
            vec![],
            vec![unit('\n', 0, 1)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-CRLF-001",
            GoldGroup::InputPreprocessing,
            1007,
            "\r\n",
            2,
            None,
            vec![token(0, 2, GoldTokenKind::Whitespace)],
            vec![],
            vec![unit('\n', 0, 2)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-FF-001",
            GoldGroup::InputPreprocessing,
            1008,
            "\u{000c}",
            1,
            None,
            vec![token(0, 1, GoldTokenKind::Whitespace)],
            vec![],
            vec![unit('\n', 0, 1)],
        ),
        GoldFixture::complete(
            "CSS-INPUT-MIXED-WHITESPACE-001",
            GoldGroup::InputPreprocessing,
            1009,
            "\n\r\r\n\u{000c} ",
            6,
            None,
            vec![token(0, 6, GoldTokenKind::Whitespace)],
            vec![],
            vec![
                unit('\n', 0, 1),
                unit('\n', 1, 2),
                unit('\n', 2, 4),
                unit('\n', 4, 5),
                unit(' ', 5, 6),
            ],
        ),
        GoldFixture::complete(
            "CSS-INPUT-NUL-MULTIBYTE-001",
            GoldGroup::InputPreprocessing,
            1010,
            "\0é:a",
            5,
            None,
            vec![
                token(0, 3, GoldTokenKind::Ident("�é")),
                token(3, 4, GoldTokenKind::Colon),
                token(4, 5, GoldTokenKind::Ident("a")),
            ],
            vec![],
            vec![
                unit('�', 0, 1),
                unit('é', 1, 3),
                unit(':', 3, 4),
                unit('a', 4, 5),
            ],
        ),
        GoldFixture::complete(
            "CSS-INPUT-MULTIBYTE-RANGES-001",
            GoldGroup::InputPreprocessing,
            1011,
            "é:a",
            4,
            None,
            vec![
                token(0, 2, GoldTokenKind::Ident("é")),
                token(2, 3, GoldTokenKind::Colon),
                token(3, 4, GoldTokenKind::Ident("a")),
            ],
            vec![],
            vec![unit('é', 0, 2), unit(':', 2, 3), unit('a', 3, 4)],
        ),
        GoldFixture::complete(
            "CSS-COMMENT-ORDER-001",
            GoldGroup::Comments,
            1101,
            "/**//**/a/**/ b",
            15,
            None,
            vec![
                closed_comment(0, 4),
                closed_comment(4, 8),
                token(8, 9, GoldTokenKind::Ident("a")),
                closed_comment(9, 13),
                token(13, 14, GoldTokenKind::Whitespace),
                token(14, 15, GoldTokenKind::Ident("b")),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-COMMENT-UNTERMINATED-001",
            GoldGroup::Comments,
            1102,
            "/*x",
            3,
            None,
            vec![eof_comment(0, 3)],
            vec![diagnostic(
                GoldDiagnosticCode::EofInComment,
                3,
                3,
                GoldDiagnosticContext::Comment,
                GoldRecovery::PreserveUnterminatedComment,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-COMMENT-CONTEXT-001",
            GoldGroup::Comments,
            1103,
            "\"/*\" url(/*)",
            12,
            None,
            vec![
                token(0, 4, GoldTokenKind::String("/*")),
                token(4, 5, GoldTokenKind::Whitespace),
                token(5, 12, GoldTokenKind::Url("/*")),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-IDENT-VARIANTS-001",
            GoldGroup::IdentEscape,
            1201,
            "a -a --a é \\g \\61  \\000061  \\61  \\0",
            36,
            None,
            vec![
                token(0, 1, GoldTokenKind::Ident("a")),
                token(1, 2, GoldTokenKind::Whitespace),
                token(2, 4, GoldTokenKind::Ident("-a")),
                token(4, 5, GoldTokenKind::Whitespace),
                token(5, 8, GoldTokenKind::Ident("--a")),
                token(8, 9, GoldTokenKind::Whitespace),
                token(9, 11, GoldTokenKind::Ident("é")),
                token(11, 12, GoldTokenKind::Whitespace),
                token(12, 14, GoldTokenKind::Ident("g")),
                token(14, 15, GoldTokenKind::Whitespace),
                token(15, 19, GoldTokenKind::Ident("a")),
                token(19, 20, GoldTokenKind::Whitespace),
                token(20, 28, GoldTokenKind::Ident("a")),
                token(28, 29, GoldTokenKind::Whitespace),
                token(29, 33, GoldTokenKind::Ident("a")),
                token(33, 34, GoldTokenKind::Whitespace),
                token(34, 36, GoldTokenKind::Ident("�")),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-IDENT-SPECIAL-001",
            GoldGroup::IdentEscape,
            1202,
            "f\\6fo( @m\\65 dia #abc #123 #\\61  1p\\78",
            38,
            None,
            vec![
                token(0, 6, GoldTokenKind::Function("foo")),
                token(6, 7, GoldTokenKind::Whitespace),
                token(7, 16, GoldTokenKind::AtKeyword("media")),
                token(16, 17, GoldTokenKind::Whitespace),
                token(
                    17,
                    21,
                    GoldTokenKind::Hash {
                        value: "abc",
                        hash_type: GoldHashType::Id,
                    },
                ),
                token(21, 22, GoldTokenKind::Whitespace),
                token(
                    22,
                    26,
                    GoldTokenKind::Hash {
                        value: "123",
                        hash_type: GoldHashType::Unrestricted,
                    },
                ),
                token(26, 27, GoldTokenKind::Whitespace),
                token(
                    27,
                    32,
                    GoldTokenKind::Hash {
                        value: "a",
                        hash_type: GoldHashType::Id,
                    },
                ),
                token(32, 33, GoldTokenKind::Whitespace),
                token(
                    33,
                    38,
                    GoldTokenKind::Dimension {
                        number: integer(None, "1"),
                        unit: "px",
                    },
                ),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-IDENT-INVALID-ESCAPE-NEWLINE-001",
            GoldGroup::IdentEscape,
            1203,
            "\\\n",
            2,
            None,
            vec![
                token(0, 1, GoldTokenKind::Delim('\\')),
                token(1, 2, GoldTokenKind::Whitespace),
            ],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidEscape,
                0,
                1,
                GoldDiagnosticContext::TokenStart,
                GoldRecovery::EmitDelimiter,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-IDENT-EOF-ESCAPE-001",
            GoldGroup::IdentEscape,
            1204,
            "\\",
            1,
            None,
            vec![token(0, 1, GoldTokenKind::Ident("�"))],
            vec![diagnostic(
                GoldDiagnosticCode::EofInEscape,
                1,
                1,
                GoldDiagnosticContext::Escape,
                GoldRecovery::SubstituteReplacementCharacterForEofEscape,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-STRING-VALID-001",
            GoldGroup::Strings,
            1301,
            "\"a\" 'a' \"\" \"a\\\"b\" \"\\61\" \"a\\\nb\" \"é\"",
            35,
            None,
            vec![
                token(0, 3, GoldTokenKind::String("a")),
                token(3, 4, GoldTokenKind::Whitespace),
                token(4, 7, GoldTokenKind::String("a")),
                token(7, 8, GoldTokenKind::Whitespace),
                token(8, 10, GoldTokenKind::String("")),
                token(10, 11, GoldTokenKind::Whitespace),
                token(11, 17, GoldTokenKind::String("a\"b")),
                token(17, 18, GoldTokenKind::Whitespace),
                token(18, 23, GoldTokenKind::String("a")),
                token(23, 24, GoldTokenKind::Whitespace),
                token(24, 30, GoldTokenKind::String("ab")),
                token(30, 31, GoldTokenKind::Whitespace),
                token(31, 35, GoldTokenKind::String("é")),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-STRING-EOF-001",
            GoldGroup::Strings,
            1302,
            "\"a",
            2,
            None,
            vec![token(0, 2, GoldTokenKind::String("a"))],
            vec![diagnostic(
                GoldDiagnosticCode::EofInString,
                2,
                2,
                GoldDiagnosticContext::String,
                GoldRecovery::EmitStringAtEndOfInput,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-STRING-NEWLINE-001",
            GoldGroup::Strings,
            1303,
            "\"a\n",
            3,
            None,
            vec![
                token(0, 2, GoldTokenKind::BadString),
                token(2, 3, GoldTokenKind::Whitespace),
            ],
            vec![diagnostic(
                GoldDiagnosticCode::NewlineInString,
                2,
                2,
                GoldDiagnosticContext::String,
                GoldRecovery::EmitBadStringAndReconsumeNewline,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-STRING-BACKSLASH-EOF-001",
            GoldGroup::Strings,
            1304,
            "\"a\\",
            3,
            None,
            vec![token(0, 3, GoldTokenKind::String("a"))],
            vec![diagnostic(
                GoldDiagnosticCode::EofInString,
                3,
                3,
                GoldDiagnosticContext::String,
                GoldRecovery::EmitStringAtEndOfInput,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-VALID-001",
            GoldGroup::Urls,
            1401,
            "url(foo) url( foo ) URL(foo) url(\"foo\") url('foo') url(/*)",
            58,
            None,
            vec![
                token(0, 8, GoldTokenKind::Url("foo")),
                token(8, 9, GoldTokenKind::Whitespace),
                token(9, 19, GoldTokenKind::Url("foo")),
                token(19, 20, GoldTokenKind::Whitespace),
                token(20, 28, GoldTokenKind::Url("foo")),
                token(28, 29, GoldTokenKind::Whitespace),
                token(29, 33, GoldTokenKind::Function("url")),
                token(33, 38, GoldTokenKind::String("foo")),
                token(38, 39, GoldTokenKind::RightParenthesis),
                token(39, 40, GoldTokenKind::Whitespace),
                token(40, 44, GoldTokenKind::Function("url")),
                token(44, 49, GoldTokenKind::String("foo")),
                token(49, 50, GoldTokenKind::RightParenthesis),
                token(50, 51, GoldTokenKind::Whitespace),
                token(51, 58, GoldTokenKind::Url("/*")),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-EOF-001",
            GoldGroup::Urls,
            1402,
            "url(a",
            5,
            None,
            vec![token(0, 5, GoldTokenKind::Url("a"))],
            vec![diagnostic(
                GoldDiagnosticCode::EofInUrl,
                5,
                5,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitUrlAtEndOfInput,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-QUOTE-001",
            GoldGroup::Urls,
            1403,
            "url(a\"b)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlCodePoint,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-ESCAPE-001",
            GoldGroup::Urls,
            1404,
            "url(a\\\n)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlEscape,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-NONPRINTABLE-001",
            GoldGroup::Urls,
            1405,
            "url(a\u{0007}b)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlCodePoint,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-EOF-ESCAPE-001",
            GoldGroup::Urls,
            1406,
            "url(a\\",
            6,
            None,
            vec![token(0, 6, GoldTokenKind::Url("a�"))],
            vec![
                diagnostic(
                    GoldDiagnosticCode::EofInEscape,
                    6,
                    6,
                    GoldDiagnosticContext::Escape,
                    GoldRecovery::SubstituteReplacementCharacterForEofEscape,
                    GoldDiagnosticSubject::LexicalItem(0),
                ),
                diagnostic(
                    GoldDiagnosticCode::EofInUrl,
                    6,
                    6,
                    GoldDiagnosticContext::Url,
                    GoldRecovery::EmitUrlAtEndOfInput,
                    GoldDiagnosticSubject::LexicalItem(0),
                ),
            ],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-WHITESPACE-CONTINUATION-001",
            GoldGroup::Urls,
            1407,
            "url(a b)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-APOSTROPHE-001",
            GoldGroup::Urls,
            1408,
            "url(a'b)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlCodePoint,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-LEFT-PAREN-001",
            GoldGroup::Urls,
            1409,
            "url(a(b)",
            8,
            None,
            vec![token(0, 8, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlCodePoint,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-URL-BAD-REMNANTS-EOF-001",
            GoldGroup::Urls,
            1410,
            "url(a\"",
            6,
            None,
            vec![token(0, 6, GoldTokenKind::BadUrl)],
            vec![diagnostic(
                GoldDiagnosticCode::InvalidUrlCodePoint,
                5,
                6,
                GoldDiagnosticContext::Url,
                GoldRecovery::EmitBadUrl,
                GoldDiagnosticSubject::LexicalItem(0),
            )],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-NUMERIC-VARIANTS-001",
            GoldGroup::Numeric,
            1501,
            "0 1 +1 -1 .5 1.5 1. 1e2 1E+2 1e-2 1% 1px 1.5px 1p\\78  123456789012345678901234567890 1e999999999999999999999999999999",
            117,
            None,
            vec![
                token(0, 1, GoldTokenKind::Number(integer(None, "0"))),
                token(1, 2, GoldTokenKind::Whitespace),
                token(2, 3, GoldTokenKind::Number(integer(None, "1"))),
                token(3, 4, GoldTokenKind::Whitespace),
                token(
                    4,
                    6,
                    GoldTokenKind::Number(integer(Some(GoldSign::Plus), "1")),
                ),
                token(6, 7, GoldTokenKind::Whitespace),
                token(
                    7,
                    9,
                    GoldTokenKind::Number(integer(Some(GoldSign::Minus), "1")),
                ),
                token(9, 10, GoldTokenKind::Whitespace),
                token(
                    10,
                    12,
                    GoldTokenKind::Number(number(None, "0", "5", None, None)),
                ),
                token(12, 13, GoldTokenKind::Whitespace),
                token(
                    13,
                    16,
                    GoldTokenKind::Number(number(None, "1", "5", None, None)),
                ),
                token(16, 17, GoldTokenKind::Whitespace),
                token(17, 18, GoldTokenKind::Number(integer(None, "1"))),
                token(18, 19, GoldTokenKind::Delim('.')),
                token(19, 20, GoldTokenKind::Whitespace),
                token(
                    20,
                    23,
                    GoldTokenKind::Number(number(None, "1", "", None, Some("2"))),
                ),
                token(23, 24, GoldTokenKind::Whitespace),
                token(
                    24,
                    28,
                    GoldTokenKind::Number(number(None, "1", "", Some(GoldSign::Plus), Some("2"))),
                ),
                token(28, 29, GoldTokenKind::Whitespace),
                token(
                    29,
                    33,
                    GoldTokenKind::Number(number(None, "1", "", Some(GoldSign::Minus), Some("2"))),
                ),
                token(33, 34, GoldTokenKind::Whitespace),
                token(34, 36, GoldTokenKind::Percentage(integer(None, "1"))),
                token(36, 37, GoldTokenKind::Whitespace),
                token(
                    37,
                    40,
                    GoldTokenKind::Dimension {
                        number: integer(None, "1"),
                        unit: "px",
                    },
                ),
                token(40, 41, GoldTokenKind::Whitespace),
                token(
                    41,
                    46,
                    GoldTokenKind::Dimension {
                        number: number(None, "1", "5", None, None),
                        unit: "px",
                    },
                ),
                token(46, 47, GoldTokenKind::Whitespace),
                token(
                    47,
                    53,
                    GoldTokenKind::Dimension {
                        number: integer(None, "1"),
                        unit: "px",
                    },
                ),
                token(53, 54, GoldTokenKind::Whitespace),
                token(
                    54,
                    84,
                    GoldTokenKind::Number(integer(None, "123456789012345678901234567890")),
                ),
                token(84, 85, GoldTokenKind::Whitespace),
                token(
                    85,
                    117,
                    GoldTokenKind::Number(number(
                        None,
                        "1",
                        "",
                        None,
                        Some("999999999999999999999999999999"),
                    )),
                ),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-FIXED-VOCABULARY-001",
            GoldGroup::Fixed,
            1601,
            "<!-- -->:;,[](){}!~",
            19,
            None,
            vec![
                token(0, 4, GoldTokenKind::Cdo),
                token(4, 5, GoldTokenKind::Whitespace),
                token(5, 8, GoldTokenKind::Cdc),
                token(8, 9, GoldTokenKind::Colon),
                token(9, 10, GoldTokenKind::Semicolon),
                token(10, 11, GoldTokenKind::Comma),
                token(11, 12, GoldTokenKind::LeftSquareBracket),
                token(12, 13, GoldTokenKind::RightSquareBracket),
                token(13, 14, GoldTokenKind::LeftParenthesis),
                token(14, 15, GoldTokenKind::RightParenthesis),
                token(15, 16, GoldTokenKind::LeftCurlyBracket),
                token(16, 17, GoldTokenKind::RightCurlyBracket),
                token(17, 18, GoldTokenKind::Delim('!')),
                token(18, 19, GoldTokenKind::Delim('~')),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-HIST-PROVENANCE-001",
            GoldGroup::Historical,
            1701,
            "a{c\\6F lor/**/:red;}",
            20,
            None,
            vec![
                token(0, 1, GoldTokenKind::Ident("a")),
                token(1, 2, GoldTokenKind::LeftCurlyBracket),
                token(2, 10, GoldTokenKind::Ident("color")),
                closed_comment(10, 14),
                token(14, 15, GoldTokenKind::Colon),
                token(15, 18, GoldTokenKind::Ident("red")),
                token(18, 19, GoldTokenKind::Semicolon),
                token(19, 20, GoldTokenKind::RightCurlyBracket),
            ],
            vec![],
            vec![],
        ),
        GoldFixture::complete(
            "CSS-HIST-PRIORITY-001",
            GoldGroup::Historical,
            1702,
            "a{color:red !/**/Im\\70 ortant;}",
            31,
            None,
            vec![
                token(0, 1, GoldTokenKind::Ident("a")),
                token(1, 2, GoldTokenKind::LeftCurlyBracket),
                token(2, 7, GoldTokenKind::Ident("color")),
                token(7, 8, GoldTokenKind::Colon),
                token(8, 11, GoldTokenKind::Ident("red")),
                token(11, 12, GoldTokenKind::Whitespace),
                token(12, 13, GoldTokenKind::Delim('!')),
                closed_comment(13, 17),
                token(17, 29, GoldTokenKind::Ident("Important")),
                token(29, 30, GoldTokenKind::Semicolon),
                token(30, 31, GoldTokenKind::RightCurlyBracket),
            ],
            vec![],
            vec![],
        ),
    ]
}

pub(super) fn resource_limit_contract_fixtures() -> Vec<GoldFixture> {
    [
        (
            "CSS-RESOURCE-SOURCE-BYTES-001",
            1901,
            GoldResourceKind::SourceBytes,
            0,
            1,
        ),
        (
            "CSS-RESOURCE-ALGORITHM-STEPS-001",
            1902,
            GoldResourceKind::AlgorithmSteps,
            1,
            2,
        ),
        (
            "CSS-RESOURCE-LEXICAL-ITEMS-001",
            1903,
            GoldResourceKind::LexicalItems,
            0,
            1,
        ),
        (
            "CSS-RESOURCE-DIAGNOSTICS-001",
            1904,
            GoldResourceKind::Diagnostics,
            0,
            1,
        ),
        (
            "CSS-RESOURCE-RETAINED-INTERPRETED-BYTES-001",
            1905,
            GoldResourceKind::RetainedInterpretedBytes,
            0,
            1,
        ),
        (
            "CSS-RESOURCE-TEMPORARY-BUFFER-BYTES-001",
            1906,
            GoldResourceKind::TemporaryBufferBytes,
            0,
            1,
        ),
    ]
    .into_iter()
    .map(|(id, source_id, kind, limit, attempted)| {
        GoldFixture::resource_limited(id, source_id, "a", 1, kind, limit, attempted)
    })
    .collect()
}
