//! Candidate-independent first-envelope gold examples.

use super::model::{
    ExpectedProcessing, ExpectedQualification, GoldFixture, GoldRange, ImplementationCoverage,
    RequestApplicability, RequestContext, SyntheticExpectation, SyntheticKind, ValidationDimension,
};

const NO_SYNTHETIC: &[SyntheticExpectation] = &[];
const ASI_EXPECTATION: &[SyntheticExpectation] = &[SyntheticExpectation {
    kind: SyntheticKind::AutomaticSemicolonInsertion,
    authored_range: None,
}];

const CORE_QUALIFICATION_DIMENSIONS: &[ValidationDimension] = &[
    ValidationDimension::Grammar,
    ValidationDimension::EarlyErrorRule,
    ValidationDimension::SourceProvenance,
    ValidationDimension::LifecycleVerdict,
    ValidationDimension::Determinism,
];

pub(crate) fn fixtures() -> Vec<GoldFixture> {
    vec![
        GoldFixture {
            id: "JS-GOLD-SCRIPT-VALID-001",
            source: "let x = 1;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: CORE_QUALIFICATION_DIMENSIONS,
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-VALID-001",
            source: "const x = 1;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: CORE_QUALIFICATION_DIMENSIONS,
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-MULTIBIND-VALID-001",
            source: "let x, y;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: CORE_QUALIFICATION_DIMENSIONS,
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-MULTIBIND-VALID-001",
            source: "const x = 1, y = 2;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: CORE_QUALIFICATION_DIMENSIONS,
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-DUPBOUNDNAMES-001",
            source: "let x, x;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(7, 8)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-MISSING-INIT-001",
            source: "const x;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(6, 7)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-SCRIPT-DUPLEXICAL-MULTIBIND-001",
            source: "let x, y; let y;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(14, 15)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-LET-MISSING-INIT-001",
            source: "const let;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(6, 9)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-DUP-MISSING-INIT-001",
            source: "const x = 1, x;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(13, 14)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-MULTIBIND-CANONICAL-DISTINCT-001",
            source: "let é, é;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::UnicodeData,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-IDENTIFIER-INIT-001",
            source: "const x = foo;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::Grammar,
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-CONST-MALFORMED-INIT-001",
            source: "const x = ;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::SyntaxRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[ValidationDimension::Grammar],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-EE04-AWAIT-YIELD-001",
            source: "let await, yield;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::ProfileContext,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-EE04-FUTURE-RESERVED-001",
            source: "let static, implements;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::ProfileContext,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-EE04-EVAL-ARGUMENTS-001",
            source: "const arguments = 1, eval = 2;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::ProfileContext,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-SCRIPT-MULTIBYTE-001",
            source: "let π = 1;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(4, 6)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::Grammar,
                ValidationDimension::UnicodeData,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-SCRIPT-DUPLEXICAL-001",
            source: "let x; let x;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(11, 12)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LEXDECL-LET-BINDING-001",
            source: "let let;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(4, 7)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ValidityDependency,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-STRICT-WITH-001",
            source: "\"use strict\"; with ({}) {}",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(14, 18)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::ProfileContext,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-SCRIPT-MODULE-SYNTAX-001",
            source: "import x from \"./x.js\";",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::SyntaxRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(0, 6)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::Grammar,
                ValidationDimension::ProfileContext,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-ANNEXB-HTML-COMMENT-001",
            source: "<!-- legacy-comment",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::ProfileBoundaryRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(0, 4)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::Grammar,
                ValidationDimension::ProfileContext,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-REGEXP-DUPFLAG-001",
            source: "var r = /a/gg;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(8, 13)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::RegExpPattern,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-REGEXP-BAD-PROPERTY-001",
            source: "var r = /\\p{Definitely_Not_A_Property}/u;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::StaticSemanticsRejected),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: Some(GoldRange::new(8, 39)),
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::EarlyErrorRule,
                ValidationDimension::RegExpPattern,
                ValidationDimension::UnicodeData,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-ASI-NO-FABRICATED-RANGE-001",
            source: "let x = 1\nx++",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: Some(ExpectedQualification::Qualified),
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: ASI_EXPECTATION,
            dimensions: &[
                ValidationDimension::Grammar,
                ValidationDimension::SourceProvenance,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LIFECYCLE-RESOURCE-LIMIT-001",
            source: "let x = 1;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: None,
            processing: ExpectedProcessing::ResourceLimited,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::LifecycleVerdict,
                ValidationDimension::Determinism,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-LIFECYCLE-INTERNAL-FAILURE-001",
            source: "let x = 1;",
            request_context: RequestContext::ScriptIndependentSource,
            applicability: RequestApplicability::Supported,
            qualification: None,
            processing: ExpectedProcessing::InternalFailure,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[ValidationDimension::LifecycleVerdict],
        },
        GoldFixture {
            id: "JS-GOLD-UNSUPPORTED-MODULE-GOAL-001",
            source: "export {};",
            request_context: RequestContext::Module,
            applicability: RequestApplicability::UnsupportedGoal,
            qualification: None,
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::ProfileContext,
                ValidationDimension::LifecycleVerdict,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-UNSUPPORTED-DIRECT-EVAL-001",
            source: "super.x",
            request_context: RequestContext::DirectEval,
            applicability: RequestApplicability::UnsupportedSourceContext,
            qualification: None,
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::ProfileContext,
                ValidationDimension::LifecycleVerdict,
            ],
        },
        GoldFixture {
            id: "JS-GOLD-UNSUPPORTED-FUNCTION-CONSTRUCTOR-001",
            source: "return 1;",
            request_context: RequestContext::FunctionConstructor,
            applicability: RequestApplicability::UnsupportedSourceContext,
            qualification: None,
            processing: ExpectedProcessing::Complete,
            implementation_coverage: ImplementationCoverage::Pending,
            subject: None,
            synthetic: NO_SYNTHETIC,
            dimensions: &[
                ValidationDimension::ProfileContext,
                ValidationDimension::LifecycleVerdict,
            ],
        },
    ]
}
